foo: bar
booleanParam: true
numericParam: 22

fileParam:
    file: README.md # will be read as utf-8, escaped and passed as string

convertParam:
    yaml: test.yml # will be read as utf-8 yaml, optionally transformed and passed as escaped string
    overwrite:
        title: "Other Title"

invalid:
    blubb: bla
    lala: lulu
binaryFileParam:
    binary: README.md # will be read as binary, base64 encoded and passed as string

keyVaultParam:
    keyVault: /subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.KeyVault/vaults/<vault-name>
    secretName: ExamplePassword

keyVaultParamWitVersion:
    keyVault: /subscriptions/<subscription-id>/resourceGroups/<rg-name>/providers/Microsoft.KeyVault/vaults/<vault-name>
    secretName: ExamplePassword
    secretVersion: cd91b2b7e10e492ebb870a6ee0591b68